thread 'main' panicked at 'Errored out creating database connection for Error { kind: Db, cause: Some(DbError { severity: "FATAL", parsed_severity: Some(Fatal), code: SqlState("28P01"), message: "password authentication failed for user \"postgres\"", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("auth.c"), line: Some(333), routine: Some("auth_failed") }) }', src\database.rs:33:23
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
